### ISSUE TITLE
Scala 2.13.4 support

### ISSUE THREAD

**Issue by mr-git** [sksamuel/scapegoat#455]
Please add Scala 2.13.4 support

**Comment by mr-git** [comment]
could somebody provide some hint on where to look to create an PR for this?

**Comment by sksamuel** [comment]
Does it not just work with the 2.13.3 plugin?

**Comment by mr-git** [comment]
it works, but there is a wish to upgrade some projects to latest Scala - 2.13.4, for which there is no binary compatible plugin...

**Comment by sksamuel** [comment]
Got it. We can release a 2.13.4 plugin.

**Comment by mr-git** [comment]
pardon, it doesn't work, there is an error like:
```
 (update) sbt.librarymanagement.ResolveException: Error downloading com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.13.4:1.4.6
```

**Comment by neko-kai** [comment]
Note: the `scapegoat-plugin-2.4.3_2.13.3` for the previous minor version, is truly binary incompatible (not just nominally due to version) - trying to reuse the older version causes a NoSuchMethodError, so it does need a recompile for 2.13.4.

```

[error] java.lang.NoSuchMethodError: 'scala.Option scala.reflect.internal.TreeInfo$Applied$.unapply(scala.reflect.internal.Trees$Tree)'
[error] com.sksamuel.scapegoat.inspections.collections.UnsafeContains$$anon$1$$anon$2.inspect(UnsafeContains.scala:44)
[error] com.sksamuel.scapegoat.InspectionContext$Traverser.traverse(Inspection.scala:104)
[error] com.sksamuel.scapegoat.InspectionContext$Traverser.traverse$(Inspection.scala:93)
[error] com.sksamuel.scapegoat.inspections.collections.UnsafeContains$$anon$1$$anon$2.traverse(UnsafeContains.scala:20)
[error] com.sksamuel.scapegoat.ScapegoatComponent$Transformer.$anonfun$transform$3(plugin.scala:249)
[error] com.sksamuel.scapegoat.ScapegoatComponent$Transformer.$anonfun$transform$3$adapted(plugin.scala:247)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] com.sksamuel.scapegoat.ScapegoatComponent$Transformer.transform(plugin.scala:247)
[error] scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:182)
```

**Comment by leedsalex** [comment]
> Got it. We can release a 2.13.4 plugin.

@sksamuel Any update on an ETA for the new release? Thank you!

**Comment by mr-git** [comment]
@sksamuel, is there a way how to help with it? maybe there is an active branch, where compilation fails and we can take a look on how to fix it?

**Comment by dbronecki** [comment]
Unfortunately there is more to do than just bumping Scala version in build.sbt. [See comment](https://github.com/scala/scala/pull/9208#issuecomment-703039173) on why scapegoat doesn't work on 2.13.4

**Comment by mwz** [comment]
Not quite closed yet as it still needs a new release, but there is `2.13.4-1.4.6+20-9ccd7405-SNAPSHOT` on [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.13.4/1.4.6+20-9ccd7405-SNAPSHOT/) for those who are impatient like me 😉

**Comment by mr-git** [comment]
Happy New Year!
When we may expect to get new release? :)

**Comment by mr-git** [comment]
👋 
When 1.4.7 release could be expected?
Compiling code with SNAPSHOT dependency feels a bit wrong ;)

**Comment by sksamuel** [comment]
1.4.7 is released.
