### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/compat/Factory$

### ISSUE THREAD

**Issue by ireactsam** [sksamuel/scapegoat#233]
Not been able to dig down what the problem is, but wanted to share for others.
In my project with this setup: `scapegoat 1.3.9` / `sbt-scapegoat 1.0.9` / `scala 2.11.12` (I know, but is Spark 2.4.0 on AWS EMR), I now get upon testing (`sbt it:test`) a runtime error:

```
[error] java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
[error] 	at scalikejdbc.DBSession$class.list(DBSession.scala:295)
[error] 	at scalikejdbc.ActiveSession.list(DBSession.scala:837)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$list$1.apply(DBSessionWrapper.scala:52)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$list$1.apply(DBSessionWrapper.scala:52)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$withAttributesSwitchedDBSession$1.apply(DBSessionWrapper.scala:34)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$withAttributesSwitchedDBSession$1.apply(DBSessionWrapper.scala:33)
[error] 	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
[error] 	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:33)
[error] 	at scalikejdbc.DBSessionWrapper.list(DBSessionWrapper.scala:52)
[error] 	at scalikejdbc.SQLToList$class.result(SQL.scala:931)
[error] 	at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
[error] 	at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
[error] 	at scalikejdbc.SQLToResult$$anonfun$14.apply(SQL.scala:811)
[error] 	at scalikejdbc.SQLToResult$$anonfun$14.apply(SQL.scala:811)
[error] 	at scalikejdbc.SQLToResult$class.apply(SQL.scala:817)
[error] 	at scalikejdbc.SQLToListImpl.apply(SQL.scala:944)
[error] 	at be.persgroep.ngage.wonka.Pipeline$$anonfun$5.apply(Pipeline.scala:471)
[error] 	at be.persgroep.ngage.wonka.Pipeline$$anonfun$5.apply(Pipeline.scala:460)
[error] 	at scalikejdbc.DBConnection$class.autoCommit(DBConnection.scala:242)
[error] 	at scalikejdbc.DB.autoCommit(DB.scala:60)
[error] 	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:216)
[error] 	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:215)
[error] 	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
[error] 	at scalikejdbc.DB$.using(DB.scala:139)
[error] 	at scalikejdbc.DB$.autoCommit(DB.scala:215)
[error] 	at be.persgroep.ngage.wonka.Pipeline$.run(Pipeline.scala:460)
[error] 	at be.persgroep.ngage.wonka.PipelineTest.beforeAll(PipelineTest.scala:133)
[error] 	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[error] 	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[error] 	at be.persgroep.ngage.wonka.PipelineTest.run(PipelineTest.scala:36)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:483)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[error] 	at sbt.TestRunner.run(TestFramework.scala:124)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:294)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.collection.compat.Factory$
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at scalikejdbc.DBSession$class.list(DBSession.scala:295)
[error] 	at scalikejdbc.ActiveSession.list(DBSession.scala:837)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$list$1.apply(DBSessionWrapper.scala:52)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$list$1.apply(DBSessionWrapper.scala:52)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$withAttributesSwitchedDBSession$1.apply(DBSessionWrapper.scala:34)
[error] 	at scalikejdbc.DBSessionWrapper$$anonfun$withAttributesSwitchedDBSession$1.apply(DBSessionWrapper.scala:33)
[error] 	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
[error] 	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:33)
[error] 	at scalikejdbc.DBSessionWrapper.list(DBSessionWrapper.scala:52)
[error] 	at scalikejdbc.SQLToList$class.result(SQL.scala:931)
[error] 	at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
[error] 	at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
[error] 	at scalikejdbc.SQLToResult$$anonfun$14.apply(SQL.scala:811)
[error] 	at scalikejdbc.SQLToResult$$anonfun$14.apply(SQL.scala:811)
[error] 	at scalikejdbc.SQLToResult$class.apply(SQL.scala:817)
[error] 	at scalikejdbc.SQLToListImpl.apply(SQL.scala:944)
[error] 	at be.persgroep.ngage.wonka.Pipeline$$anonfun$5.apply(Pipeline.scala:471)
[error] 	at be.persgroep.ngage.wonka.Pipeline$$anonfun$5.apply(Pipeline.scala:460)
[error] 	at scalikejdbc.DBConnection$class.autoCommit(DBConnection.scala:242)
[error] 	at scalikejdbc.DB.autoCommit(DB.scala:60)
[error] 	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:216)
[error] 	at scalikejdbc.DB$$anonfun$autoCommit$1.apply(DB.scala:215)
[error] 	at scalikejdbc.LoanPattern$class.using(LoanPattern.scala:18)
[error] 	at scalikejdbc.DB$.using(DB.scala:139)
[error] 	at scalikejdbc.DB$.autoCommit(DB.scala:215)
[error] 	at be.persgroep.ngage.wonka.Pipeline$.run(Pipeline.scala:460)
[error] 	at be.persgroep.ngage.wonka.PipelineTest.beforeAll(PipelineTest.scala:133)
[error] 	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[error] 	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[error] 	at be.persgroep.ngage.wonka.PipelineTest.run(PipelineTest.scala:36)
[error] 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:483)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[error] 	at sbt.TestRunner.run(TestFramework.scala:124)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:294)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (IntegrationTest / executeTests) java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
```

Reverting back to Scapegoat 1.3.8 fixes it....

**Comment by poslegm** [comment]
Also about compat problem: don't use sbt-scapegoat v1.0.9 with scalikejdbc v3.0.4!

I had `NoSuchMethodError` because of `scala-collection-compat` versions inconsistency.

Full error text for search engines:
```
java.lang.NoSuchMethodError: scalikejdbc.SQLBatch.apply(Lscalikejdbc/DBSession;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;
```

**Comment by avdv** [comment]
@ireactsam could you re-test with 1.3.11 or 1.4.0 please?

**Comment by ireactsam** [comment]
@avdv the problem actually went away when upgrading scalikejdbc from 3.3.5 to 3.4.0. I tried 1.3.11 with the newer scalikejdbc and didn't had this problem anymore.

**Comment by mccartney** [comment]
So I consider this obsolete.
